### ISSUE TITLE
export-notes-as-website doesn't appear to be working on Windows 11.

### ISSUE THREAD

**Issue by bvn9ne** [qownnotes/scripts#177] opened 2022-11-18 18:18 UTC
This pertains to export-notes-as-website from [dohliam](https://github.com/qownnotes/scripts/commits?author=dohliam).
#### Expected behaviour

The script should create the export folder and convert all files to html.

#### Actual behaviour

It says that all files are successfully exported but the export folder isn't created and files are not converted. Looking at the qml, I have seen two issues that may be the cause. 

First, the mkdir uses the -p flag which isn't an available flag on Windows.

Second, the output of the exported notes looks like this:
Successfully exported note: E:/repos/bivs/Realms (BIVS Original)/O-Series (Oikoumene)/O02.00 – BIVS Big Book of Mythic Beasts/A - Notes.md\A - Notes

In the above example, it looks like it is improperly parsing the subfolder name from the regex replace.

I tested it a hard-coded temp solution for the regex replace and pre-created output directories and it wrote the html to them as expected.

#### Steps to reproduce

Install plugin (export-notes-as-website). Run plugin via context menu or custom actions menu.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
I apologize. I removed the logs because it said it exceeded the 65536 character limitations. This is for the best anyway, I had to remove a large portion due to confidential information. I can provide a personal instance with a sanitized output if needed.
```
</details>

**Comment by pbek** [comment] 2022-11-18 19:13
@dohliam, are you sure your script was intended for all platforms according to https://github.com/qownnotes/scripts/blob/master/export-notes-as-website/info.json#L6? 😉

**Comment by dohliam** [comment] 2022-11-18 19:29
Yes, this script has not been tested on Windows and the `info.json` should probably be corrected to indicate that until this issue has been fixed.

I don't have a Windows machine to test this on, but from what @bvn9ne described it looks like it should be fairly simple to fix this by adding a check for the operating system and using a different regex if it is found to be running on Windows.

**Comment by pbek** [comment] 2022-11-21 08:02
I guess it was fixed now by @bvn9ne, so I'll close this. 😉

**Closed by pbek** 2022-11-21 08:02 UTC
Labels: Type: Support
